# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b53dc2571f99cab8bb9c4153877b4360b81daa0863ad2eeca2e143157dfb45b882bfd0b26727b5d7444c972f83731b07e8d3b68a71aa71a0b4e8ef864d89e83c

test:
  secret_key_base: 4b76e381c0644a3a1e86f773deb019016bac07cc9aba6ac87a611596ba0141b682a9916746087f594dbe02257e2c7dfa78512d51d0d000317d0e13e522d3adb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
